#!/bin/sh
if [ $(id -u) -ne 0 ]; then
	echo "Error: Usted no es root. Solo root puede usar $0"
	exit 1
fi

echo "Instalador de Paquetes, Version 0.10"
printf "(c)2020 pocketlinux32, debajo GPLv3\n\n"

case $1 in
	"install" | "instalar")
		shift
		for pkg in $@; do
			echo "Instalando paquete $pkg"
			install $pkg /opt/pkg
		done
		;;
	"remove" | "remover")
		cd
		shift
		for pkg in $@; do
			echo "Removiendo paquete $pkg"
			rm -f /opt/pkg/$pkg
		done
		;;
esac
