#!/bin/sh
if [ $(id -u) -ne 0 ]; then
	echo "Error: Usted no es root. Necesita ser root para poder usar $0"
	exit 1
fi

case $1 in
	"install" | "instalar")
		shift
		for pkg in $@; do
			echo "Instalando paquete $pkg"
			install $pkg /opt/pkg
		done
		;;
	"remove" | "remover")
		cd
		shift
		for pkg in $@; do
			echo "Removiendo paquete $pkg"
			rm -f /opt/pkg/$pkg
		done
		;;
esac
