#!/bin/sh

################################
#                              #
# mkinitrd, Version 0.01       #
# Creada en 28-09-2020         #
# PocketNES Software (gpl)2020 #
#                              #
################################

echo "mkinitrd, Version 0.01"
echo "(gpl)2020 PocketNES Software, debajo GPLv3\n"

#Chequea todos los parametros
while [ $# -gt 0 ]; do
	case $1 in
		--busybox)
			shift
			busybox=$1
			;;
		--init)
			shift
			init=$1
			;;
		--type)
			shift
			type=$1
			;;
		--compression)
			shift
			compression=$1
			;;
		--help)
			echo "mkinitrd es un script que crea ramdisks iniciales. Aqui estan algunas de las opciones"
			echo "que le puedes dar al script:\n"
			echo "--busybox	La ruta de BusyBox"
			echo "--init		La ruta del script de init"
			echo "--type		Define el tipo de initrd (rd, ramfs)"
			echo "--compression	Define el tipo de compresion (gzip, bzip2, xz)"
			echo "--help		Mostrar esta ayuda\n"
			exit 0
			;;
		*)
			echo "Error: Parametro desconoscido '$1'. Escriba $0 --help para mostrar ayuda."
			exit 1
	esac
	shift
done

#Chequea parametros requeridos
if [ "$busybox" = "" ]; then
	echo "Error: --busybox es requirido."
	exit 2
elif [ "$init" = "" ]; then
	echo "Error: --init es requirido."
	exit 3
fi


